// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
lv_obj_t *ui_ScreenHome;
lv_obj_t *ui_LabelSpeed;
lv_obj_t *ui_ArcSpeed;
lv_obj_t *ui_LabelBitcoin;
lv_obj_t *ui_LabelChange;
lv_obj_t *ui_LabelStatus;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_background_420_[1] = {&ui_img_background_420_380_png};
const lv_img_dsc_t *ui_imgset_1613556616[1] = {&ui_img_1926738670};
const lv_img_dsc_t *ui_imgset_[1] = {&ui_img_01_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenHome_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenHome);
}
