// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t *ui_ScreenHome;
extern lv_obj_t *ui_LabelSpeed;
extern lv_obj_t *ui_ArcSpeed;
extern lv_obj_t *ui_LabelBitcoin;
extern lv_obj_t *ui_LabelChange;
extern lv_obj_t *ui_LabelStatus;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_download_png);   // assets/download.png
LV_IMG_DECLARE( ui_img_background_420_380_png);   // assets/background_420_380.png
LV_IMG_DECLARE( ui_img_1926738670);   // assets/black-wifi-icon-32.png
LV_IMG_DECLARE( ui_img_01_png);   // assets/01.png
LV_IMG_DECLARE( ui_img_bitcoin_logo);   // Clean Bitcoin logo 48x48
LV_IMG_DECLARE( ui_img_bitcoin_background);   // Bitcoin background 800x480



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
