// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenHome_screen_init(void)
{
ui_ScreenHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
// Set dark gradient background
lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenHome, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_ScreenHome, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

// Bitcoin logo (top of screen, centered)
ui_LabelBitcoin = lv_label_create(ui_ScreenHome);
lv_obj_set_width(ui_LabelBitcoin, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelBitcoin, LV_SIZE_CONTENT);
lv_obj_set_align(ui_LabelBitcoin, LV_ALIGN_TOP_MID);
lv_obj_set_y(ui_LabelBitcoin, 60);
lv_label_set_text(ui_LabelBitcoin, "BITCOIN");
lv_obj_set_style_text_color(ui_LabelBitcoin, lv_color_hex(0xF7931A), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_opa(ui_LabelBitcoin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBitcoin, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_LabelBitcoin, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

// Bitcoin logo image (positioned above the text)
lv_obj_t * ui_ImgBitcoin = lv_img_create(ui_ScreenHome);
lv_obj_set_width(ui_ImgBitcoin, LV_SIZE_CONTENT);
lv_obj_set_height(ui_ImgBitcoin, LV_SIZE_CONTENT);
lv_obj_set_align(ui_ImgBitcoin, LV_ALIGN_TOP_MID);
lv_obj_set_y(ui_ImgBitcoin, 10);
lv_img_set_src(ui_ImgBitcoin, &ui_img_bitcoin_logo);

// Main price display (center of screen)
ui_LabelSpeed = lv_label_create(ui_ScreenHome);
lv_obj_set_width( ui_LabelSpeed, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelSpeed, LV_SIZE_CONTENT);
lv_obj_set_align( ui_LabelSpeed, LV_ALIGN_CENTER );
lv_obj_set_y(ui_LabelSpeed, -20);
lv_label_set_text(ui_LabelSpeed,"Loading...");
lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

// Price change container (transparent, no background)
lv_obj_t * ui_ChangeContainer = lv_obj_create(ui_ScreenHome);
lv_obj_set_width(ui_ChangeContainer, 150);
lv_obj_set_height(ui_ChangeContainer, 35);
lv_obj_set_align(ui_ChangeContainer, LV_ALIGN_CENTER);
lv_obj_set_y(ui_ChangeContainer, 30);
lv_obj_clear_flag(ui_ChangeContainer, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_opa(ui_ChangeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ChangeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_all(ui_ChangeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

// Price change label (inside the container)
ui_LabelChange = lv_label_create(ui_ChangeContainer);
lv_obj_set_width(ui_LabelChange, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelChange, LV_SIZE_CONTENT);
lv_obj_set_align(ui_LabelChange, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelChange, "-- --%");
lv_obj_set_style_text_color(ui_LabelChange, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_opa(ui_LabelChange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelChange, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

// Status label at bottom
ui_LabelStatus = lv_label_create(ui_ScreenHome);
lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);
lv_obj_set_align(ui_LabelStatus, LV_ALIGN_BOTTOM_MID);
lv_obj_set_y(ui_LabelStatus, -30);
lv_label_set_text(ui_LabelStatus, "Live Price - Connecting...");
lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

// Keep ui_ArcSpeed for compatibility but make it invisible
ui_ArcSpeed = lv_arc_create(ui_ScreenHome);
lv_obj_set_width( ui_ArcSpeed, 10);
lv_obj_set_height( ui_ArcSpeed, 10);
lv_obj_set_x( ui_ArcSpeed, -1000); // Move far off screen
lv_obj_set_y( ui_ArcSpeed, -1000);
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcSpeed, 0,45);
lv_arc_set_value(ui_ArcSpeed, 22);
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_ArcSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_ArcSpeed, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

}
